services:
  grimoire:
    image: goniszewski/grimoire:develop
    container_name: grimoire
    restart: unless-stopped
    environment:
      # Set this to your domain name (default: http://localhost:5173)
      # Example: PUBLIC_ORIGIN=grimoire.mydomain.com
      - PUBLIC_ORIGIN=http://localhost:5173
      # Set this to true if you're using HTTPS (default: false)
      # Example: PUBLIC_HTTPS_ONLY=true
      - PUBLIC_HTTPS_ONLY=false
      # Change to the port you want the app to listen on (default: 5173)
      # Example: PORT=80
      - PORT=5173
      # Set this to true if you want to disable public signups (default: false)
      - PUBLIC_SIGNUP_DISABLED=false
    volumes:
      - grimoire_data:/app/data/
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '$PORT:$PORT'
volumes:
  grimoire_data:
    external: false
